# Generated by Django 4.1.3 on 2023-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_product_employee_company_manager_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_product',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(related_name='cust', to='app1.product'),
        ),
    ]
