# Generated by Django 4.1.3 on 2023-02-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customerproduct_alter_customer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
    ]
